[theme]
base = "dark"
primaryColor = "#587792"
backgroundColor = "#E2DDCA"
secondaryBackgroundColor = "#587792"
textColor = "#06353E"
font = "monospace"
headingFont = "monospace"
baseRadius = "10px"
borderColor = "#587792"
showWidgetBorder = true

[ui]
hideSidebarNav = true
